name: Continuous Integration

on:
  push:
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Unit & Feature Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Up containers
        run: ./run up -d

      - name: Setup Application
        run: |
          ./run key:generate
          ./run install

      - name: Run Tests
        run: ./run test

  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install
        
      - name: Up containers
        run: ./run up -d

      - name: PSR-4 Checker
        run: ./run composer dump-autoload --optimize --strict-psr

      - name: Laravel Pint
        run: ./run pint --test